version: "3.9"

services:
  # ----------- INTERNET (Landing pública) -----------
  landing:
    build: ./landing
    container_name: doggiechic_landing
    ports:
      - "80:80"
    networks:
      - publica
    restart: unless-stopped

  # ----------- INTRANET (Panel interno) -----------
  intranet:
    build: ./intranet
    container_name: doggiechic_intranet
    ports:
      - "8080:80"
    networks:
      - privada
    restart: unless-stopped

  # ----------- BACKEND (API interna) -----------
  backend:
    build: ./backend
    container_name: doggiechic_backend
    expose:
      - "4000"
    ports:
      - "4000:4000" # Mapeado para poder acceder desde local para pruebas (en produccion seria solo expose)
    environment:
      DB_URI: mongodb://mongodb:27017/doggiechic
    networks:
      - privada
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      - mongodb
    restart: unless-stopped

  # ----------- DATABASE (MongoDB) -----------
  mongodb:
    image: mongo:6
    container_name: doggiechic_mongodb
    ports:
      - "27017:27017" # Solo para dev local
    networks:
      - privada
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

networks:
  publica:
  privada:
    internal: false   # false para poder probar localmente, en AWS se controla por Security Group

volumes:
  mongodb_data:
